version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx:alpine
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - web