version: '3.8'

services:
  flask:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    privileged: true
    command: /bin/sh -c "sysctl vm.overcommit_memory=1 && redis-server /usr/local/etc/redis/redis.conf"


  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8443:443"
    depends_on:
      - flask